# Generated by Django 4.1.3 on 2022-11-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateTimeField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=50)),
                ('code_postal', models.IntegerField()),
                ('membre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Rentrez votre nom', max_length=50)),
                ('prenom', models.CharField(help_text='Rentrez votre prénom', max_length=50)),
                ('date_naissance', models.DateTimeField(help_text='Rentrez votre date de naissance', max_length=50)),
                ('mail', models.CharField(help_text='Rentrez votre adresse email', max_length=50)),
                ('telephone', models.CharField(help_text='Rentrez votre numéro de téléphone', max_length=20)),
                ('adresse', models.CharField(help_text='Rentrez votre adresse', max_length=50)),
                ('code_postal', models.IntegerField(help_text='Rentrez votre code postal')),
                ('date_inscription', models.DateTimeField(max_length=50)),
                ('fiche_inscription', models.BinaryField(max_length=50)),
                ('certificat_medical', models.BinaryField(help_text='Ajoutez votre certificat médical', max_length=50)),
                ('date_certificat', models.DateTimeField(max_length=50)),
                ('autorisation_parentale', models.BinaryField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tkt')),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
                ('idAdherant', models.ManyToManyField(related_name='adherant', to='inscription.adherants')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('idAdherant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhenrant', to='inscription.adherants')),
            ],
        ),
        migrations.AddField(
            model_name='adherants',
            name='idInscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription', to='inscription.inscription'),
        ),
    ]
