# Generated by Django 4.1.3 on 2022-11-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherants',
            name='idInscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.inscription'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='idAdherant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.adherants'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='idAdherant',
            field=models.ManyToManyField(to='inscription.adherants'),
        ),
    ]
