# Generated by Django 4.1.3 on 2022-11-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_alter_adherants_idinscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='autorisation_parentale',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='certificat_medical',
            field=models.ImageField(help_text='Ajoutez votre certificat médical', max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_certificat',
            field=models.DateTimeField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fiche_inscription',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
    ]
