# Generated by Django 4.1.4 on 2022-12-10 18:37

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_alter_inscription_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='adresse',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='code_postal',
            field=django_cryptography.fields.encrypt(models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_naissance',
            field=django_cryptography.fields.encrypt(models.DateTimeField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='mail',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prenom',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
    ]
