# Generated by Django 4.1.4 on 2022-12-10 18:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_alter_inscription_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='code_postal',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=5)),
        ),
    ]
